services:
  app:
    image: fortylashes/pingerang:latest 
    command: sh -c "xvfb-run -a ./pingerang"
    ports:
      - 4000:4000
    environment:
      - MYSQL_USER=${MYSQL_USER:-web}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?database password not set}
    depends_on:
      mysql:
        condition: service_healthy  # Waits for the healthcheck to pass
  mysql:
    image: mysql:8.0
    volumes:
      - pingerang-mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?database password not set}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-pingerang}
      - MYSQL_USER=${MYSQL_USER:-web}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?database password not set}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-psecret"]
      interval: 3s
      timeout: 3s
      retries: 10
volumes:
  pingerang-mysql-data:
